### ISSUE TITLE
`replicate model show` segfaults if the model has no versions

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cli#78]
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x86a3b6]

goroutine 1 [running]:
github.com/replicate/cli/internal/cmd/model.init.func4(0xd8f940, {0xc000192150, 0x4?, 0x94b1d4?})
	/tmp/cli-0.7.1/internal/cmd/model/show.go:77 +0x4d6
github.com/spf13/cobra.(*Command).execute(0xd8f940, {0xc000192120, 0x1, 0x1})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xd8c860)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/replicate/cli/cmd/replicate.Execute()
	/tmp/cli-0.7.1/cmd/replicate/main.go:27 +0x1a
main.main()
	/tmp/cli-0.7.1/main.go:6 +0xf
```

**Comment by mattt** [comment]
This is fixed in [v0.7.2](https://github.com/replicate/cli/releases/tag/v0.7.2)
